package com.example.springrest.entity;

import jakarta.persistence.*;
import java.time.LocalDate;
import java.time.LocalDateTime;

import com.fasterxml.jackson.annotation.JsonIgnore;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Table(name = "employee")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Employee {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // DB: GENERATED BY DEFAULT AS IDENTITY
    @Column(name = "id")
    private Integer id;

    @Column(name = "firstname", length = 20)
    private String firstname;

    @Column(name = "lastname", length = 20)
    private String lastname;

    @Column(name = "description", length = 255)
    private String description;

    @Column(name = "job_level")
    private Integer jobLevel;

    @Column(name = "created_date", insertable = false, updatable = false)
    private LocalDate createdDate;

    @Column(name = "last_updated", insertable = false, updatable = false)
    private LocalDateTime lastUpdated;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "manager_id", foreignKey = @ForeignKey(name = "fk_manager"))
    @JsonIgnore // to avoid circular reference during JSON serialization
    private Manager manager;

    // Jackson (the JSON serializer) tries to walk through the entire object graph
    // to convert it to JSON.
    // Circular problems happen when you have bi-directional relationships,
    // e.g., Employee -> Manager -> Employee -> Manager ...

}
